Bubble_Sort/bubble_sort.py
Merge sort/merge_sort.py

Added Bubble sort

---

Stack/stack.py

stack added

---

In Cpp/catalan.cpp

Hey, I added catalan Number Algo

catalan Added

---

Sorting methods/Bubble_Sort/bubble_sort.py
Sorting methods/Merge sort/merge_sort.py

All sorting methods are updated in single folder

new folder created

---

In Python/stack_rpn.py

Submitting my code for Hacktoberfest!

adding RPN implementation using stacks in Python

---

Tree/Binary tree right view

Binary tree right view

---

In Python/0-1knapsack.py

0-1 knapsack code in python #17

Create 0-1knapsack.py #17

---

Trie/trie.cpp

created trie data structure in cpp

Created Trie Data Structure

---

In Cpp/QuickSort.cpp

Implemented Quick Sorting in cpp.

Added QuickSort.cpp in In Cpp/ folder

---

In Cpp/RadixSort.cpp

Hybrid sorting (Radix + Bucket).

Implemented Radix Sort using Bucket Sort

---

Dynamic programming/Maximal square

Adding a programming which find the maximal square in a binary matrix with just 1.

Create Maximal square

---

In Cpp/kadaneAlgorithm.cpp

UserName:- manishmotwani2002
Language :- C++
Topic:- DSA-Arrays
Added a optimal solution of Kadane's Algorithm used for evaluating "Largest Sum Contiguous Subarray" Problem.
Appropriate comments are added in the code.

C++ Code for Kadane's Algorithm

---

Tree/topView

Closes issue #28 
@AjinkyaSahu please merge it

Top View of binary tree

---

Dynamic programming/longest_increasing_subsequence_dp.cpp

Bottom-Up DP solution of Longest Increasing Subsequence problem

Created longest_increasing_subsequence_dp.cpp

---

Tree/bottom-view.cpp
Tree/topView

Closes issue #29 
@AjinkyaSahu please merge it

Bottom view of binary tree

---

In Cpp/reverseString.cpp
Tree/bottom-view.cpp
Tree/findValue in BST
Tree/topView

Closes #31 
@AjinkyaSahu please merge it

Reverse a string

---

Tree/bottom-view.cpp
Tree/findValue in BST
Tree/topView

Closes #30 
@AjinkyaSahu please merge it

Find value in bst

---

DoublyLinkedList/DLinkedList.cpp
In Cpp/template.cpp
LinkedList/LinkedList.cpp
Queue/queueUsingStack.cpp
Stack/stackImplement.cpp

Added linked list, doubly linked list and stack implementation!

Added linked list, doubly linked list and stack implementation

---

In Cpp/Find the unique element.cpp

Unique element.cpp

---

In Python/prims.py

Added prims Algorithm in Python.

---

README.md

The README.md now provides a better insight into the guidelines set by **Digital Ocean** for the **Hacktoberfest2021**

Discrepancy in README.md removed and guidelines updated

---

In Cpp/Check palindrome(recursively).cpp

Application of Recursion and String

Added question check palindrome(recursively).cpp

---

In Cpp/All indices of number.cpp

Added question all indices of number with solution

---

In Cpp/Does s contains t.cpp

question focuses on application of string

Added ques does s contains t with solution

---

Tree/Sum of nodes at level k.cpp

The code for sum of nodes at level k(A variation of BFS) has been added with full explanation on comments using C++.Please view it. Successful merging of PR would lead to resolution of the issue  #47.

The code has been added with easy explanation in C++.

---

Tree/inheritance.c

An example of inheritance in Trees

Created tree inheritance

---

Dynamic programming/minEditSeq.cpp

Minimum Edit Sequence code using Dynamic Programming with C++

Added Minimum Edit Sequence
